name: wasm

# This rule triggers when the workflow will run
on:
  # run the workflow manually from Actions tab
  workflow_dispatch:

# jobs can run in sequence or parallel in a workflow
jobs:
  # This single job is called "build"
  build:
    # Specify the operating system for the runner job
    runs-on: ubuntu-latest
    env:
      git_hash: $(git rev-parse --short "$GITHUB_SHA")

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # the job gets runned into $GITHUB_WORKSPACE, that is the environment variable for the repo
      - name: Access current repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Build docker image
        run: |
          docker run  -d -p 5000:5000 --name registry registry:2.7
          # env git_hash env goes into the compose.yml
          docker compose -f ./compose.yml --progress=plain build wasm
          docker push localhost:5000/kjtwasm:01
          #podman build -t kjtwasm:01 -f ./Dockerfile.wasm


      - name: Retrieve artifact from docker image
        run: |
          docker run -it --name kjtwasm -d localhost:5000/kjtwasm:latest
          docker cp kjtwasm:./wasmgui ${{ github.workspace }}/artifacts/

      - name: Archive the build artifact
        uses: actions/upload-artifact@v3
        with:
          name: wasmgui
          path: ${{ github.workspace }}/artifacts/wasmgui

